-- MySQL Script generated by MySQL Workbench
-- Fri May  3 22:20:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BaseDatosSaludContigo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BaseDatosSaludContigo` ;

-- -----------------------------------------------------
-- Schema BaseDatosSaludContigo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BaseDatosSaludContigo` DEFAULT CHARACTER SET utf8mb4 ;
USE `BaseDatosSaludContigo` ;


-- -----------------------------------------------------
-- Table `BaseDatosSaludContigo`.`Administradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BaseDatosSaludContigo`.`Administradores` ;

CREATE TABLE IF NOT EXISTS `BaseDatosSaludContigo`.`Administradores` (
  `IdAdministrador` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `Tipo_Documento` VARCHAR(20) NOT NULL,
  `Numero_Documento` VARCHAR(20) NOT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Sexo` VARCHAR(20) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(200) NOT NULL,
  `Ocupacion` VARCHAR(100) NOT NULL,
  `Username` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(20) NOT NULL,
  `Estado` VARCHAR(10) NOT NULL,
  `Rol` VARCHAR(10) NOT NULL,
  `Fecha_Creacion` DATE NULL DEFAULT NULL,
  `Fecha_Modificacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`IdAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseDatosSaludContigo`.`Medicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BaseDatosSaludContigo`.`Medicos` ;

CREATE TABLE IF NOT EXISTS `BaseDatosSaludContigo`.`Medicos` (
  `IdMedico` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `Tipo_Documento` VARCHAR(20) NOT NULL,
  `Numero_Documento` VARCHAR(20) NOT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Sexo` VARCHAR(20) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(200) NOT NULL,
  `Especialidad` VARCHAR(100) NOT NULL,
  `Username` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(20) NOT NULL,
  `Estado` VARCHAR(10) NOT NULL,
  `Fecha_Creacion` DATE NULL DEFAULT NULL,
  `Fecha_Modificacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`IdMedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseDatosSaludContigo`.`Pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BaseDatosSaludContigo`.`Pacientes` ;

CREATE TABLE IF NOT EXISTS `BaseDatosSaludContigo`.`Pacientes` (
  `IdPaciente` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `Tipo_Documento` VARCHAR(20) NOT NULL,
  `Numero_Documento` VARCHAR(20) NOT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Sexo` VARCHAR(20) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(200) NOT NULL,
  `Ocupacion` VARCHAR(100) NOT NULL,
  `Username` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(20) NOT NULL,
  `Estado` VARCHAR(10) NOT NULL,
  `Fecha_Creacion` DATE NULL DEFAULT NULL,
  `Fecha_Modificacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`IdPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseDatosSaludContigo`.`Citas_Medicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BaseDatosSaludContigo`.`Citas_Medicas` ;

CREATE TABLE IF NOT EXISTS `BaseDatosSaludContigo`.`Citas_Medicas` (
  `IdCita` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Cita` VARCHAR(50) NOT NULL,
  `Fecha_Cita` DATE NOT NULL,
  `Hora_Cita` TIME NOT NULL,
  `Lugar_Cita` VARCHAR(200) NOT NULL,
  `Estado_Cita` VARCHAR(20) NOT NULL,
  `Observacion_Cita` VARCHAR(200) NULL DEFAULT NULL,
  `Pacientes_IdPaciente` INT NOT NULL,
  `Medicos_IdMedico` INT NOT NULL,
  PRIMARY KEY (`IdCita`),
  CONSTRAINT `fk_Citas_Medicas_Medicos1`
    FOREIGN KEY (`Medicos_IdMedico`)
    REFERENCES `BaseDatosSaludContigo`.`Medicos` (`IdMedico`)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Citas_Medicas_Pacientes1`
    FOREIGN KEY (`Pacientes_IdPaciente`)
    REFERENCES `BaseDatosSaludContigo`.`Pacientes` (`IdPaciente`)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Citas_Medicas_Pacientes1_idx` ON `BaseDatosSaludContigo`.`Citas_Medicas` (`Pacientes_IdPaciente` ASC) VISIBLE;
CREATE INDEX `fk_Citas_Medicas_Medicos1_idx` ON `BaseDatosSaludContigo`.`Citas_Medicas` (`Medicos_IdMedico` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `BaseDatosSaludContigo`.`Examenes_Medicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BaseDatosSaludContigo`.`Examenes_Medicos` ;

CREATE TABLE IF NOT EXISTS `BaseDatosSaludContigo`.`Examenes_Medicos` (
  `IdExamen` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Examen` VARCHAR(50) NOT NULL,
  `Fecha_Examen` DATE NOT NULL,
  `Hora_Examen` TIME NOT NULL,
  `Lugar_Examen` VARCHAR(200) NOT NULL,
  `Estado_Examen` VARCHAR(20) NOT NULL,
  `Observacion_Examen` VARCHAR(200) NULL DEFAULT NULL,
  `Pacientes_IdPaciente` INT NOT NULL,
  `Medicos_IdMedico` INT NOT NULL,
  PRIMARY KEY (`IdExamen`),
  CONSTRAINT `fk_Examenes_Medicos_Medicos1`
    FOREIGN KEY (`Medicos_IdMedico`)
    REFERENCES `BaseDatosSaludContigo`.`Medicos` (`IdMedico`)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Examenes_Medicos_Pacientes1`
    FOREIGN KEY (`Pacientes_IdPaciente`)
    REFERENCES `BaseDatosSaludContigo`.`Pacientes` (`IdPaciente`)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Examenes_Medicos_Pacientes1_idx` ON `BaseDatosSaludContigo`.`Examenes_Medicos` (`Pacientes_IdPaciente` ASC) VISIBLE;
CREATE INDEX `fk_Examenes_Medicos_Medicos1_idx` ON `BaseDatosSaludContigo`.`Examenes_Medicos` (`Medicos_IdMedico` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `BaseDatosSaludContigo`.`Historias_Clinicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BaseDatosSaludContigo`.`Historias_Clinicas` ;

CREATE TABLE IF NOT EXISTS `BaseDatosSaludContigo`.`Historias_Clinicas` (
  `IdHistoria` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Historia` DATE NOT NULL,
  `Antecedentes_Historia` VARCHAR(500) NULL DEFAULT NULL,
  `Examenes_Historia` VARCHAR(500) NULL DEFAULT NULL,
  `Diagnostico_Historia` VARCHAR(500) NULL DEFAULT NULL,
  `Tratamiento_Historia` VARCHAR(500) NULL DEFAULT NULL,
  `Pacientes_IdPaciente` INT NOT NULL,
  `Medicos_IdMedico` INT NOT NULL,
  PRIMARY KEY (`IdHistoria`),
  CONSTRAINT `fk_Historias_Clinicas_Medicos1`
    FOREIGN KEY (`Medicos_IdMedico`)
    REFERENCES `BaseDatosSaludContigo`.`Medicos` (`IdMedico`)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historias_Clinicas_Pacientes1`
    FOREIGN KEY (`Pacientes_IdPaciente`)
    REFERENCES `BaseDatosSaludContigo`.`Pacientes` (`IdPaciente`)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Historias_Clinicas_Pacientes1_idx` ON `BaseDatosSaludContigo`.`Historias_Clinicas` (`Pacientes_IdPaciente` ASC) VISIBLE;
CREATE INDEX `fk_Historias_Clinicas_Medicos1_idx` ON `BaseDatosSaludContigo`.`Historias_Clinicas` (`Medicos_IdMedico` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
COMMIT;


-- -----------------------------------------------------
-- Inserts `BaseDatosSaludContigo`.`Administradores`
-- -----------------------------------------------------
INSERT INTO Administradores (Nombres, Apellidos, Tipo_Documento, Numero_Documento, Fecha_Nacimiento, Sexo, Telefono, Correo, Direccion, Ocupacion, Username, Password, Estado, Rol, Fecha_Creacion) 
VALUES 
('Elias', 'Contreras', 'CC', '110200002112', '1993-12-21', 'Masculino', '123456789', 'elias_contreras@mail.com', 'Calle 123 #45-67, Bogotá', 'Administrador', 'admin1', 'admin1', 'Activo', '0', NOW()),
('María', 'López', 'CC', '110200000001', '1992-08-20', 'Femenino', '123456789', 'maria_lopez@mail.com', 'Carrera 78 #90-12, Medellín', 'Administrador', 'Admin2', 'admin2', 'Activo', '1', NOW()),
('Carlos', 'Ramírez', 'CC', '110200000002', '1990-11-10', 'Masculino', '123456789', 'carlos_ramirez@mail.com', 'Diagonal 56 #34-21, Cali', 'Administrador', 'admin3', 'admin3', 'Activo', '1', NOW()),
('Laura', 'Hernández', 'CC', '110200000003', '1995-02-28', 'Femenino', '123456789', 'laura_hernandez@mail.com', 'Avenida 12 #10-45, Barranquilla', 'Administrador', 'admin4', 'admin4', 'Activo', '2', NOW()),
('Andrés', 'Gómez', 'CC', '110200000004', '1991-07-03', 'Masculino', '123456789', 'andres_gomez@mail.com', 'Calle 56 #34-90, Cartagena', 'Administrador', 'admin5', 'admin5', 'Activo', '2', NOW());
COMMIT;


-- -----------------------------------------------------
-- Inserts `BaseDatosSaludContigo`.`Pacientes`
-- -----------------------------------------------------
INSERT INTO Pacientes (Nombres, Apellidos, Tipo_Documento, Numero_Documento, Fecha_Nacimiento, Sexo, Telefono, Correo, Direccion, Ocupacion, Username, Password, Estado, Fecha_Creacion) 
VALUES 
('Juan Carlos', 'Gómez López', 'CC', '110200000001', '1992-04-05', 'Masculino', '123456789', 'juan_carlos_gomez@mail.com', 'Calle 23 #45-67, Bogotá', 'Estudiante', 'juan.gomez', 'CC110200000001', 'Activo', NOW()),
('María Alejandra', 'Hernández Rodríguez', 'CC', '110200000002', '1993-06-10', 'Femenino', '123456789', 'maria_alejandra_hernandez@mail.com', 'Carrera 56 #12-34, Medellín', 'Ingeniero', 'maria.hernandez', 'CC110200000002', 'Activo', NOW()),
('Luis Felipe', 'Martínez García', 'CC', '110200000003', '1991-08-15', 'Masculino', '123456789', 'luis_felipe_martinez@mail.com', 'Diagonal 78 #90-12, Cali', 'Abogado', 'luis.martinez', 'CC110200000003', 'Activo', NOW()),
('Ana Sofía', 'Pérez Sánchez', 'CC', '110200000004', '1990-10-25', 'Femenino', '123456789', 'ana_sofia_perez@mail.com', 'Calle 12 #56-78, Barranquilla', 'Médico', 'ana.perez', 'CC110200000004', 'Activo', NOW()),
('Diego Alejandro', 'Rojas Vargas', 'CC', '110200000005', '1994-01-05', 'Masculino', '123456789', 'diego_alejandro_rojas@mail.com', 'Carrera 90 #34-56, Cartagena', 'Profesor', 'diego.rojas', 'CC110200000005', 'Activo', NOW()),
('Valeria Camila', 'Gutiérrez López', 'CC', '110200000006', '1993-04-12', 'Femenino', '123456789', 'valeria_camila_gutierrez@mail.com', 'Diagonal 45 #56-78, Bogotá', 'Empresario', 'valeria.gutierrez', 'CC110200000006', 'Activo', NOW()),
('Andrés Felipe', 'Sánchez Ramírez', 'CC', '110200000007', '1992-07-20', 'Masculino', '123456789', 'andres_felipe_sanchez@mail.com', 'Calle 78 #90-12, Medellín', 'Cajero', 'andres.sanchez', 'CC110200000007', 'Activo', NOW()),
('Laura Valentina', 'Cárdenas González', 'CC', '110200000008', '1995-09-30', 'Femenino', '123456789', 'laura_valentina_cardenas@mail.com', 'Carrera 34 #12-34, Cali', 'Arquitecto', 'laura.cardenas', 'CC110200000008', 'Activo', NOW()),
('Javier Eduardo', 'Herrera López', 'CC', '110200000009', '1994-11-10', 'Masculino', '123456789', 'javier_eduardo_herrera@mail.com', 'Diagonal 67 #78-90, Barranquilla', 'Diseñador', 'javier.herrera', 'CC110200000009', 'Activo', NOW()),
('Laura Sofía', 'Rojas Gómez', 'CC', '110200000010', '1990-12-25', 'Femenino', '123456789', 'laura_sofia_rojas@mail.com', 'Avenida 23 #56-78, Cartagena', 'Programador', 'laura.rojas', 'CC110200000010', 'Activo', NOW()),
('Carlos Andrés', 'Sánchez Martínez', 'CC', '110200000011', '1993-02-03', 'Masculino', '123456789', 'carlos_andres_sanchez@mail.com', 'Calle 78 #90-12, Bogotá', 'Chef', 'carlos.sanchez', 'CC110200000011', 'Activo', NOW()),
('Valentina María', 'Gómez Herrera', 'CC', '110200000012', '1995-04-10', 'Femenino', '123456789', 'valentina_maria_gomez@mail.com', 'Carrera 45 #12-34, Medellín', 'Estudiante', 'valentina.gomez', 'CC110200000012', 'Activo', NOW()),
('Andrés Felipe', 'Martínez Ortega', 'CC', '110200000013', '1994-06-15', 'Masculino', '123456789', 'andres_felipe_martinez@mail.com', 'Diagonal 56 #90-12, Cali', 'Músico', 'andres.martinez', 'CC110200000013', 'Activo', NOW()),
('Laura María', 'González Vargas', 'CC', '110200000014', '1990-08-25', 'Femenino', '123456789', 'laura_maria_gonzalez@mail.com', 'Calle 34 #56-78, Barranquilla', 'Actor', 'laura.gonzalez', 'CC110200000014', 'Activo', NOW()),
('Felipe Andrés', 'Vargas Hernández', 'CC', '110200000015', '1992-10-30', 'Masculino', '123456789', 'felipe_andres_vargas@mail.com', 'Carrera 67 #90-12, Cartagena', 'Cocinero', 'felipe.vargas', 'CC110200000015', 'Activo', NOW()),
('María Paula', 'Hernández Gómez', 'CC', '110200000016', '1991-12-12', 'Femenino', '123456789', 'maria_paula_hernandez@mail.com', 'Diagonal 12 #34-56, Bogotá', 'Piloto', 'maria.hernandez', 'CC110200000016', 'Activo', NOW()),
('Jorge Luis', 'Rodríguez Martínez', 'CC', '110200000017', '1993-03-20', 'Masculino', '123456789', 'jorge_luis_rodriguez@mail.com', 'Carrera 78 #56-78, Medellín', 'Ingeniero', 'jorge.rodriguez', 'CC110200000017', 'Activo', NOW()),
('Paula Andrea', 'López Rodríguez', 'CC', '110200000018', '1990-05-15', 'Femenino', '123456789', 'paula_andrea_lopez@mail.com', 'Calle 45 #90-12, Cali', 'Abogado', 'paula.lopez', 'CC110200000018', 'Activo', NOW()),
('Andrés Felipe', 'Gómez Martínez', 'CC', '110200000019', '1994-07-28', 'Masculino', '123456789', 'andres_felipe_gomez@mail.com', 'Diagonal 56 #34-56, Barranquilla', 'Médico', 'andres.gomez', 'CC110200000019', 'Activo', NOW()),
('María José', 'Herrera López', 'CC', '110200000020', '1995-09-10', 'Femenino', '123456789', 'maria_jose_herrera@mail.com', 'Avenida 10 #78-90, Cartagena', 'Profesor', 'maria.herrera', 'CC110200000020', 'Activo', NOW()),
('Camila Sofía', 'Gómez López', 'CC', '110200000021', '1992-04-05', 'Femenino', '123456789', 'camila_sofia_gomez@mail.com', 'Calle 23 #45-67, Bogotá', 'Estudiante', 'camila.gomez', 'CC110200000021', 'Activo', NOW()),
('Jorge Alberto', 'Hernández Rodríguez', 'CC', '110200000022', '1993-06-10', 'Masculino', '123456789', 'jorge_alberto_hernandez@mail.com', 'Carrera 56 #12-34, Medellín', 'Ingeniero', 'jorge.hernandez', 'CC110200000022', 'Activo', NOW()),
('Luisa Fernanda', 'Martínez García', 'CC', '110200000023', '1991-08-15', 'Femenino', '123456789', 'luisa_fernanda_martinez@mail.com', 'Diagonal 78 #90-12, Cali', 'Abogado', 'luisa.martinez', 'CC110200000023', 'Activo', NOW()),
('Javier Alejandro', 'Pérez Sánchez', 'CC', '110200000024', '1990-10-25', 'Masculino', '123456789', 'javier_alejandro_perez@mail.com', 'Calle 12 #56-78, Barranquilla', 'Médico', 'javier.perez', 'CC110200000024', 'Activo', NOW()),
('María Paula', 'Rojas Vargas', 'CC', '110200000025', '1994-01-05', 'Femenino', '123456789', 'maria_paula_rojas@mail.com', 'Carrera 90 #34-56, Cartagena', 'Profesor', 'maria.rojas', 'CC110200000025', 'Activo', NOW()),
('Carlos Andrés', 'Gutiérrez López', 'CC', '110200000026', '1993-04-12', 'Masculino', '123456789', 'carlos_andres_gutierrez@mail.com', 'Diagonal 45 #56-78, Bogotá', 'Empresario', 'carlos.gutierrez', 'CC110200000026', 'Activo', NOW()),
('Valentina María', 'Sánchez Ramírez', 'CC', '110200000027', '1992-07-20', 'Femenino', '123456789', 'valentina_maria_sanchez@mail.com', 'Calle 78 #90-12, Medellín', 'Cajero', 'valentina.sanchez', 'CC110200000027', 'Activo', NOW()),
('Andrea Carolina', 'Cárdenas González', 'CC', '110200000028', '1995-09-30', 'Femenino', '123456789', 'andrea_carolina_cardenas@mail.com', 'Carrera 34 #12-34, Cali', 'Arquitecto', 'andrea.cardenas', 'CC110200000028', 'Activo', NOW()),
('Luisa Fernanda', 'Herrera López', 'CC', '110200000029', '1994-11-10', 'Femenino', '123456789', 'luisa_fernanda_herrera@mail.com', 'Diagonal 67 #78-90, Barranquilla', 'Diseñador', 'luisa.herrera', 'CC110200000029', 'Activo', NOW()),
('Carlos Eduardo', 'Rojas Gómez', 'CC', '110200000030', '1990-12-25', 'Masculino', '123456789', 'carlos_eduardo_rojas@mail.com', 'Avenida 23 #56-78, Cartagena', 'Programador', 'carlos.rojas', 'CC110200000030', 'Activo', NOW()),
('Sofía Alejandra', 'Sánchez Martínez', 'CC', '110200000031', '1993-02-03', 'Femenino', '123456789', 'sofia_alejandra_sanchez@mail.com', 'Calle 78 #90-12, Bogotá', 'Chef', 'sofia.sanchez', 'CC110200000031', 'Activo', NOW()),
('Andrea Carolina', 'Gómez Herrera', 'CC', '110200000032', '1995-04-10', 'Femenino', '123456789', 'andrea_carolina_gomez@mail.com', 'Carrera 45 #12-34, Medellín', 'Estudiante', 'andrea.gomez', 'CC110200000032', 'Activo', NOW()),
('María José', 'Martínez Ortega', 'CC', '110200000033', '1994-06-15', 'Femenino', '123456789', 'maria_jose_martinez@mail.com', 'Diagonal 56 #90-12, Cali', 'Músico', 'maria.martinez', 'CC110200000033', 'Activo', NOW()),
('Andrea Carolina', 'González Vargas', 'CC', '110200000034', '1990-08-25', 'Femenino', '123456789', 'andrea_carolina_gonzalez@mail.com', 'Calle 34 #56-78, Barranquilla', 'Actor', 'andrea.gonzalez', 'CC110200000034', 'Activo', NOW()),
('Javier Alejandro', 'Vargas Hernández', 'CC', '110200000035', '1992-10-30', 'Masculino', '123456789', 'javier_alejandro_vargas@mail.com', 'Carrera 67 #90-12, Cartagena', 'Cocinero', 'javier.vargas', 'CC110200000035', 'Activo', NOW()),
('Juan Carlos', 'Hernández Gómez', 'CC', '110200000036', '1991-12-12', 'Masculino', '123456789', 'juan_carlos_hernandez@mail.com', 'Diagonal 12 #34-56, Bogotá', 'Piloto', 'juan.hernandez', 'CC110200000036', 'Activo', NOW()),
('Jorge Alberto', 'Rodríguez Martínez', 'CC', '110200000037', '1993-03-20', 'Masculino', '123456789', 'jorge_alberto_rodriguez@mail.com', 'Carrera 78 #56-78, Medellín', 'Ingeniero', 'jorge.rodriguez', 'CC110200000037', 'Activo', NOW()),
('María Alejandra', 'López Rodríguez', 'CC', '110200000038', '1990-05-15', 'Femenino', '123456789', 'maria_alejandra_lopez@mail.com', 'Calle 45 #90-12, Cali', 'Abogado', 'maria.lopez', 'CC110200000038', 'Activo', NOW()),
('Luis Felipe', 'Gómez Martínez', 'CC', '110200000039', '1994-07-28', 'Masculino', '123456789', 'luis_felipe_gomez@mail.com', 'Diagonal 56 #34-56, Barranquilla', 'Médico', 'luis.gomez', 'CC110200000039', 'Activo', NOW()),
('Camila Sofía', 'Herrera López', 'CC', '110200000040', '1995-09-10', 'Femenino', '123456789', 'camila_sofia_herrera@mail.com', 'Avenida 10 #78-90, Cartagena', 'Profesor', 'camila.herrera', 'CC110200000040', 'Activo', NOW()),
('Andrea Carolina', 'Gómez López', 'CC', '110200000041', '1992-04-05', 'Femenino', '123456789', 'andrea_carolina_gomez@mail.com', 'Calle 23 #45-67, Bogotá', 'Estudiante', 'andrea.gomez', 'CC110200000041', 'Activo', NOW()),
('María José', 'Hernández Rodríguez', 'CC', '110200000042', '1993-06-10', 'Femenino', '123456789', 'maria_jose_hernandez@mail.com', 'Carrera 56 #12-34, Medellín', 'Ingeniero', 'maria.hernandez', 'CC110200000042', 'Activo', NOW()),
('Luis Felipe', 'Martínez García', 'CC', '110200000043', '1991-08-15', 'Masculino', '123456789', 'luis_felipe_martinez@mail.com', 'Diagonal 78 #90-12, Cali', 'Abogado', 'luis.martinez', 'CC110200000043', 'Activo', NOW()),
('Ana Sofía', 'Pérez Sánchez', 'CC', '110200000044', '1990-10-25', 'Femenino', '123456789', 'ana_sofia_perez@mail.com', 'Calle 12 #56-78, Barranquilla', 'Médico', 'ana.perez', 'CC110200000044', 'Activo', NOW()),
('Diego Alejandro', 'Rojas Vargas', 'CC', '110200000045', '1994-01-05', 'Masculino', '123456789', 'diego_alejandro_rojas@mail.com', 'Carrera 90 #34-56, Cartagena', 'Profesor', 'diego.rojas', 'CC110200000045', 'Activo', NOW()),
('Valeria Camila', 'Gutiérrez López', 'CC', '110200000046', '1993-04-12', 'Femenino', '123456789', 'valeria_camila_gutierrez@mail.com', 'Diagonal 45 #56-78, Bogotá', 'Empresario', 'valeria.gutierrez', 'CC110200000046', 'Activo', NOW()),
('Andrés Felipe', 'Sánchez Ramírez', 'CC', '110200000047', '1992-07-20', 'Masculino', '123456789', 'andres_felipe_sanchez@mail.com', 'Calle 78 #90-12, Medellín', 'Cajero', 'andres.sanchez', 'CC110200000047', 'Activo', NOW()),
('Laura Valentina', 'Cárdenas González', 'CC', '110200000048', '1995-09-30', 'Femenino', '123456789', 'laura_valentina_cardenas@mail.com', 'Carrera 34 #12-34, Cali', 'Arquitecto', 'laura.cardenas', 'CC110200000048', 'Activo', NOW()),
('Javier Eduardo', 'Herrera López', 'CC', '110200000049', '1994-11-10', 'Masculino', '123456789', 'javier_eduardo_herrera@mail.com', 'Diagonal 67 #78-90, Barranquilla', 'Diseñador', 'javier.herrera', 'CC110200000049', 'Activo', NOW()),
('Laura Sofía', 'Rojas Gómez', 'CC', '110200000050', '1990-12-25', 'Femenino', '123456789', 'laura_sofia_rojas@mail.com', 'Avenida 23 #56-78, Cartagena', 'Programador', 'laura.rojas', 'CC110200000050', 'Activo', NOW());
COMMIT;


-- -----------------------------------------------------
-- Inserts `BaseDatosSaludContigo`.`Medicos`
-- -----------------------------------------------------
INSERT INTO Medicos (Nombres, Apellidos, Tipo_Documento, Numero_Documento, Fecha_Nacimiento, Sexo, Telefono, Correo, Direccion, Especialidad, Username, Password, Estado, Fecha_Creacion) 
VALUES 
('Juan Carlos', 'Gómez López', 'CC', '100300000020', '1992-04-05', 'Masculino', '123456789', 'juan_carlos_gomez@mail.com', 'Calle 23 #45-67, Bogotá', 'Pediatría', 'juan.gomez', 'CC100300000020', 'Activo', NOW()),
('María Alejandra', 'Hernández Rodríguez', 'CC', '100300000021', '1993-06-10', 'Femenino', '123456789', 'maria_alejandra_hernandez@mail.com', 'Carrera 56 #12-34, Medellín', 'Pediatría', 'maria.hernandez', 'CC100300000021', 'Activo', NOW()),
('Luis Felipe', 'Martínez García', 'CC', '100300000022', '1991-08-15', 'Masculino', '123456789', 'luis_felipe_martinez@mail.com', 'Diagonal 78 #90-12, Cali', 'Dermatología', 'luis.martinez', 'CC100300000022', 'Activo', NOW()),
('Ana Sofía', 'Pérez Sánchez', 'CC', '100300000023', '1990-10-25', 'Femenino', '123456789', 'ana_sofia_perez@mail.com', 'Calle 12 #56-78, Barranquilla', 'Dermatología', 'ana.perez', 'CC100300000023', 'Activo', NOW()),
('Diego Alejandro', 'Rojas Vargas', 'CC', '100300000024', '1994-01-05', 'Masculino', '123456789', 'diego_alejandro_rojas@mail.com', 'Carrera 90 #34-56, Cartagena', 'Cardiología', 'diego.rojas', 'CC100300000024', 'Activo', NOW()),
('Valeria Camila', 'Gutiérrez López', 'CC', '100300000025', '1993-04-12', 'Femenino', '123456789', 'valeria_camila_gutierrez@mail.com', 'Diagonal 45 #56-78, Bogotá', 'Cardiología', 'valeria.gutierrez', 'CC100300000025', 'Activo', NOW()),
('Andrés Felipe', 'Sánchez Ramírez', 'CC', '100300000026', '1992-07-20', 'Masculino', '123456789', 'andres_felipe_sanchez@mail.com', 'Calle 78 #90-12, Medellín', 'Oftalmología', 'andres.sanchez', 'CC100300000026', 'Activo', NOW()),
('Laura Valentina', 'Cárdenas González', 'CC', '100300000027', '1995-09-30', 'Femenino', '123456789', 'laura_valentina_cardenas@mail.com', 'Carrera 34 #12-34, Cali', 'Oftalmología', 'laura.cardenas', 'CC100300000027', 'Activo', NOW()),
('Javier Eduardo', 'Herrera López', 'CC', '100300000028', '1994-11-10', 'Masculino', '123456789', 'javier_eduardo_herrera@mail.com', 'Diagonal 67 #78-90, Barranquilla', 'Gastroenterología', 'javier.herrera', 'CC100300000028', 'Activo', NOW()),
('Laura Sofía', 'Rojas Gómez', 'CC', '100300000029', '1990-12-25', 'Femenino', '123456789', 'laura_sofia_rojas@mail.com', 'Avenida 23 #56-78, Cartagena', 'Endocrinología', 'laura.rojas', 'CC100300000029', 'Activo', NOW()),
('Carlos Andrés', 'Sánchez Martínez', 'CC', '100300000030', '1993-02-03', 'Masculino', '123456789', 'carlos_andres_sanchez@mail.com', 'Calle 78 #90-12, Bogotá', 'Medicina General', 'carlos.sanchez', 'CC100300000030', 'Activo', NOW()),
('Valentina María', 'Gómez Herrera', 'CC', '100300000031', '1995-04-10', 'Femenino', '123456789', 'valentina_maria_gomez@mail.com', 'Carrera 45 #12-34, Medellín', 'Medicina General', 'valentina.gomez', 'CC100300000031', 'Activo', NOW()),
('Andrés Felipe', 'Martínez Ortega', 'CC', '100300000032', '1994-06-15', 'Masculino', '123456789', 'andres_felipe_martinez@mail.com', 'Diagonal 56 #90-12, Cali', 'Medicina General', 'andres.martinez', 'CC100300000032', 'Activo', NOW()),
('Laura María', 'González Vargas', 'CC', '100300000033', '1990-08-25', 'Femenino', '123456789', 'laura_maria_gonzalez@mail.com', 'Calle 34 #56-78, Barranquilla', 'Medicina General', 'laura.gonzalez', 'CC100300000033', 'Activo', NOW()),
('Felipe Andrés', 'Vargas Hernández', 'CC', '100300000034', '1992-10-30', 'Masculino', '123456789', 'felipe_andres_vargas@mail.com', 'Carrera 67 #90-12, Cartagena', 'Medicina General', 'felipe.vargas', 'CC100300000034', 'Activo', NOW()),
('María Paula', 'Hernández Gómez', 'CC', '100300000035', '1991-12-12', 'Femenino', '123456789', 'maria_paula_hernandez@mail.com', 'Diagonal 12 #34-56, Bogotá', 'Medicina General', 'maria.hernandez', 'CC100300000035', 'Activo', NOW()),
('Jorge Luis', 'Rodríguez Martínez', 'CC', '100300000036', '1993-03-20', 'Masculino', '123456789', 'jorge_luis_rodriguez@mail.com', 'Carrera 78 #56-78, Medellín', 'Medicina General', 'jorge.rodriguez', 'CC100300000036', 'Activo', NOW()),
('Paula Andrea', 'López Rodríguez', 'CC', '100300000037', '1990-05-15', 'Femenino', '123456789', 'paula_andrea_lopez@mail.com', 'Calle 45 #90-12, Cali', 'Medicina General', 'paula.lopez', 'CC100300000037', 'Activo', NOW()),
('Andrés Felipe', 'Gómez Martínez', 'CC', '100300000038', '1994-07-28', 'Masculino', '123456789', 'andres_felipe_gomez@mail.com', 'Diagonal 56 #34-56, Barranquilla', 'Medicina General', 'andres.gomez', 'CC100300000038', 'Activo', NOW()),
('María José', 'Herrera López', 'CC', '100300000039', '1995-09-10', 'Femenino', '123456789', 'maria_jose_herrera@mail.com', 'Avenida 10 #78-90, Cartagena', 'Medicina General', 'maria.herrera', 'CC100300000039', 'Activo', NOW());
COMMIT;


-- -----------------------------------------------------
-- Inserts `BaseDatosSaludContigo`.`Citas_Medicas`
-- -----------------------------------------------------
INSERT INTO Citas_Medicas (Tipo_Cita, Fecha_Cita, Hora_Cita, Lugar_Cita, Estado_Cita, Pacientes_IdPaciente, Medicos_IdMedico) 
VALUES 
('Consulta', '2024-03-01', '08:00:00', 'Centro Médico Norte, Bogotá', 'Agendada', 1, 1), 
('Control', '2024-03-15', '09:30:00', 'Hospital San Juan, Medellín', 'Agendada', 1, 2), 
('Seguimiento', '2024-03-28', '10:45:00', 'Clínica del Sur, Cali', 'Agendada', 1, 3), 
('Consulta', '2024-03-02', '08:30:00', 'Clínica del Este, Barranquilla', 'Ejecutada', 2, 4), 
('Control', '2024-03-16', '10:00:00', 'Hospital Central, Cartagena', 'Ejecutada', 2, 5), 
('Seguimiento', '2024-03-29', '11:15:00', 'Centro de Salud Occidente, Bogotá', 'Ejecutada', 2, 6), 
('Consulta', '2024-03-03', '09:00:00', 'Clínica Suramericana, Medellín', 'Cancelada', 3, 7), 
('Control', '2024-03-17', '10:30:00', 'Centro Médico del Valle, Cali', 'Cancelada', 3, 8), 
('Seguimiento', '2024-03-30', '11:45:00', 'Hospital Universitario, Bogotá', 'Cancelada', 3, 9), 
('Consulta', '2024-03-04', '08:15:00', 'Clínica El Poblado, Medellín', 'Agendada', 4, 10), 
('Control', '2024-03-18', '09:45:00', 'Hospital San Francisco, Cali', 'Agendada', 4, 11), 
('Seguimiento', '2024-03-31', '11:00:00', 'Centro de Salud La Floresta, Barranquilla', 'Agendada', 4, 12), 
('Consulta', '2024-03-05', '08:45:00', 'Hospital San Ignacio, Bogotá', 'Ejecutada', 5, 13), 
('Control', '2024-03-19', '10:15:00', 'Clínica del Caribe, Cartagena', 'Ejecutada', 5, 14), 
('Seguimiento', '2024-03-01', '11:30:00', 'Hospital de la Misericordia, Medellín', 'Ejecutada', 5, 15),
('Consulta', '2024-03-06', '08:00:00', 'Centro Médico Norte, Bogotá', 'Agendada', 6, 1), 
('Control', '2024-03-20', '09:30:00', 'Hospital San Juan, Medellín', 'Agendada', 6, 2), 
('Seguimiento', '2024-03-02', '10:45:00', 'Clínica del Sur, Cali', 'Agendada', 6, 3), 
('Consulta', '2024-03-07', '08:30:00', 'Clínica del Este, Barranquilla', 'Ejecutada', 7, 4), 
('Control', '2024-03-21', '10:00:00', 'Hospital Central, Cartagena', 'Ejecutada', 7, 5), 
('Seguimiento', '2024-03-03', '11:15:00', 'Centro de Salud Occidente, Bogotá', 'Ejecutada', 7, 6), 
('Consulta', '2024-03-08', '09:00:00', 'Clínica Suramericana, Medellín', 'Cancelada', 8, 7), 
('Control', '2024-03-22', '10:30:00', 'Centro Médico del Valle, Cali', 'Cancelada', 8, 8), 
('Seguimiento', '2024-03-04', '11:45:00', 'Hospital Universitario, Bogotá', 'Cancelada', 8, 9), 
('Consulta', '2024-03-09', '08:15:00', 'Clínica El Poblado, Medellín', 'Agendada', 9, 10), 
('Control', '2024-03-23', '09:45:00', 'Hospital San Francisco, Cali', 'Agendada', 9, 11), 
('Seguimiento', '2024-03-05', '11:00:00', 'Centro de Salud La Floresta, Barranquilla', 'Agendada', 9, 12), 
('Consulta', '2024-03-10', '08:45:00', 'Hospital San Ignacio, Bogotá', 'Ejecutada', 10, 13), 
('Control', '2024-03-24', '10:15:00', 'Clínica del Caribe, Cartagena', 'Ejecutada', 10, 14), 
('Seguimiento', '2024-03-06', '11:30:00', 'Hospital de la Misericordia, Medellín', 'Ejecutada', 10, 15);
COMMIT;


-- -----------------------------------------------------
-- Inserts `BaseDatosSaludContigo`.`Examenes_Medicos`
-- -----------------------------------------------------
INSERT INTO Examenes_Medicos (Tipo_Examen, Fecha_Examen, Hora_Examen, Lugar_Examen, Estado_Examen, Pacientes_IdPaciente, Medicos_IdMedico) 
VALUES 
('Análisis de sangre', '2024-03-01', '08:00:00', 'Laboratorio Clínico Central, Bogotá', 'Agendado', 1, 16), 
('Radiografía de tórax', '2024-03-15', '09:30:00', 'Centro de Imágenes del Norte, Medellín', 'Agendado', 1, 17), 
('Ecocardiograma', '2024-03-28', '10:45:00', 'Clínica Cardiovascular del Sur, Cali', 'Agendado', 1, 18), 
('Examen de vista', '2024-03-02', '08:30:00', 'Centro Oftalmológico del Este, Barranquilla', 'Agendado', 2, 19), 
('Electrocardiograma', '2024-03-16', '10:00:00', 'Centro Cardiológico Central, Cartagena', 'Agendado', 2, 20), 
('Colonoscopia', '2024-03-29', '11:15:00', 'Centro de Gastroenterología del Norte, Bogotá', 'Agendado', 2, 1), 
('Prueba de esfuerzo', '2024-03-03', '09:00:00', 'Centro Cardiológico Suramericano, Medellín', 'Agendado', 3, 2), 
('Tomografía computarizada', '2024-03-17', '10:30:00', 'Centro de Diagnóstico del Valle, Cali', 'Agendado', 3, 3), 
('Resonancia magnética', '2024-03-30', '11:45:00', 'Centro de Imágenes Diagnósticas del Norte, Bogotá', 'Agendado', 3, 4), 
('Colonoscopia', '2024-03-04', '08:15:00', 'Centro de Gastroenterología del Sur, Medellín', 'Agendado', 4, 5), 
('Endoscopia', '2024-03-18', '09:45:00', 'Centro de Endoscopias del Valle, Cali', 'Agendado', 4, 6), 
('Ecografía abdominal', '2024-03-31', '11:00:00', 'Centro de Ecografías La Floresta, Barranquilla', 'Agendado', 4, 7), 
('Examen de audición', '2024-03-05', '08:45:00', 'Centro Auditivo del Norte, Bogotá', 'Agendado', 5, 8), 
('Tomografía cerebral', '2024-03-19', '10:15:00', 'Centro de Diagnóstico de la Costa, Cartagena', 'Agendado', 5, 9), 
('Resonancia magnética', '2024-03-01', '11:30:00', 'Centro de Imágenes del Sur, Medellín', 'Agendado', 5, 10),
('Espirometría', '2024-03-06', '08:00:00', 'Centro de Neumología Central, Bogotá', 'Agendado', 6, 11), 
('Electroencefalograma', '2024-03-20', '09:30:00', 'Centro de Neurología del Norte, Medellín', 'Agendado', 6, 12), 
('Resonancia magnética', '2024-03-02', '10:45:00', 'Centro de Imágenes Diagnósticas del Sur, Cali', 'Agendado', 6, 13), 
('Prueba de esfuerzo', '2024-03-07', '08:30:00', 'Centro Cardiológico del Este, Barranquilla', 'Agendado', 7, 14), 
('Radiografía ósea', '2024-03-21', '10:00:00', 'Centro de Radiología Central, Cartagena', 'Agendado', 7, 15), 
('Ecocardiograma', '2024-03-03', '11:15:00', 'Clínica Cardiovascular del Norte, Bogotá', 'Agendado', 7, 16), 
('Endoscopia', '2024-03-08', '09:00:00', 'Centro de Endoscopias del Sur, Medellín', 'Agendado', 8, 17), 
('Ecografía renal', '2024-03-22', '10:30:00', 'Centro de Ecografías Renales, Cali', 'Agendado', 8, 18), 
('Tomografía computarizada', '2024-03-04', '11:45:00', 'Centro de Imágenes del Este, Bogotá', 'Agendado', 8, 19), 
('Espirometría', '2024-03-09', '08:15:00', 'Centro de Neumología Sur, Medellín', 'Agendado', 9, 20), 
('Colonoscopia', '2024-03-23', '09:45:00', 'Centro de Gastroenterología del Centro, Cali', 'Agendado', 9, 1), 
('Radiografía de columna', '2024-03-05', '11:00:00', 'Centro de Radiología de la Costa, Barranquilla', 'Agendado', 9, 2), 
('Ecografía abdominal', '2024-03-10', '08:45:00', 'Centro de Ecografías del Norte, Bogotá', 'Agendado', 10, 3), 
('Resonancia magnética', '2024-03-24', '10:15:00', 'Centro de Imágenes Diagnósticas del Centro, Cartagena', 'Agendado', 10, 4), 
('Electroencefalograma', '2024-03-06', '11:30:00', 'Centro de Neurología del Este, Medellín', 'Agendado', 10, 5);
COMMIT;


-- -----------------------------------------------------
-- Inserts `BaseDatosSaludContigo`.`Historias_Clinicas`
-- -----------------------------------------------------
INSERT INTO Historias_Clinicas (Fecha_Historia, Antecedentes_Historia, Examenes_Historia, Diagnostico_Historia, Tratamiento_Historia, Pacientes_IdPaciente, Medicos_IdMedico)
VALUES
-- Paciente 1 (3 registros)
('2023-12-01', 'El paciente ha experimentado fatiga y falta de aliento durante los últimos meses. No hay antecedentes de enfermedades cardíacas en la familia.', 'Análisis de sangre, Radiografía de tórax', 'Se sospecha de anemia debido a los resultados de los análisis de sangre. La radiografía de tórax muestra una posible infección pulmonar.', 'Se prescribe un tratamiento con suplementos de hierro y un antibiótico para la infección pulmonar.', 1, 16),
('2023-11-15', 'El paciente ha experimentado dolores de cabeza frecuentes y mareos. No hay antecedentes de enfermedades neurológicas en la familia.', 'Electroencefalograma', 'El electroencefalograma revela actividad cerebral anormal, sugiriendo posibles convulsiones.', 'Se recomienda un tratamiento antiepiléptico y se derivará al paciente a un neurólogo para un seguimiento especializado.', 1, 12),
('2023-10-05', 'El paciente ha experimentado dolor abdominal intenso y pérdida de peso inexplicable en las últimas semanas.', 'Ecografía abdominal', 'La ecografía abdominal revela la presencia de un tumor en el hígado.', 'Se requiere una biopsia para confirmar el diagnóstico y se discutirán opciones de tratamiento una vez que se conozcan los resultados.', 1, 7),

-- Paciente 2 (4 registros)
('2023-12-02', 'El paciente presenta problemas de visión y dificultad para leer de cerca. No hay antecedentes de enfermedades oculares en la familia.', 'Examen de vista', 'Se diagnostica miopía en ambos ojos, con una graduación de -3 dioptrías en el ojo derecho y -2.5 dioptrías en el ojo izquierdo.', 'Se recomienda el uso de anteojos con las especificaciones proporcionadas y se realizará un seguimiento oftalmológico anual.', 2, 19),
('2023-11-18', 'El paciente experimenta dolor en el pecho y dificultad para respirar durante el ejercicio. No hay antecedentes de enfermedades cardíacas en la familia.', 'Prueba de esfuerzo', 'La prueba de esfuerzo muestra signos de isquemia miocárdica, indicando una posible enfermedad coronaria.', 'Se derivará al paciente a un cardiólogo para una evaluación más detallada y posiblemente a una angiografía coronaria.', 2, 14),
('2023-09-25', 'El paciente ha tenido problemas digestivos, incluyendo dolor abdominal y diarrea crónica. No hay antecedentes de enfermedades gastrointestinales en la familia.', 'Colonoscopia, Endoscopia', 'La colonoscopia y la endoscopia revelan signos de inflamación en el colon y el intestino delgado, sugiriendo enfermedad inflamatoria intestinal.', 'Se prescribirá un tratamiento con medicamentos antiinflamatorios y se recomendará una dieta específica baja en fibra.', 2, 5),
('2023-08-10', 'El paciente ha experimentado problemas de audición y zumbidos en los oídos. No hay antecedentes de enfermedades auditivas en la familia.', 'Audiometría', 'La audiometría muestra pérdida de audición en frecuencias altas, indicando posible daño en el oído interno.', 'Se recomendará el uso de audífonos y se realizará un seguimiento audiológico regular.', 2, 19),

-- Paciente 3 (5 registros)
('2023-11-28', 'El paciente ha experimentado episodios de desmayo y mareos. No hay antecedentes de convulsiones en la familia.', 'Electrocardiograma', 'El electrocardiograma muestra una arritmia cardíaca con intervalos PR prolongados, indicando un posible bloqueo cardíaco.', 'Se requiere un monitoreo cardíaco continuo y se considerará la colocación de un marcapasos si persisten los síntomas.', 3, 2),
('2023-10-15', 'El paciente ha experimentado dificultad para respirar y opresión en el pecho. No hay antecedentes de enfermedades cardíacas en la familia.', 'Prueba de esfuerzo', 'La prueba de esfuerzo muestra una respuesta anormal del corazón al ejercicio, indicando posible angina de pecho.', 'Se derivará al paciente a un cardiólogo para una evaluación más detallada y se discutirán opciones de tratamiento.', 3, 16),
('2023-09-10', 'El paciente ha experimentado dolor articular y rigidez, especialmente por la mañana. No hay antecedentes de enfermedades reumáticas en la familia.', 'Análisis de sangre', 'Los análisis de sangre muestran niveles elevados de factor reumatoide y PCR, indicando posible artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos antiinflamatorios y se realizará un seguimiento regular con un reumatólogo.', 3, 4),
('2023-08-05', 'El paciente ha experimentado fatiga extrema y pérdida de peso sin causa aparente. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Biopsia de médula ósea', 'La biopsia de médula ósea revela signos de anemia aplásica, una enfermedad autoinmune que afecta la producción de células sanguíneas.', 'Se requerirá tratamiento con medicamentos inmunosupresores y se discutirá la posibilidad de un trasplante de médula ósea.', 3, 10),
('2023-07-20', 'El paciente ha experimentado inflamación y dolor en las articulaciones, especialmente en las manos y las rodillas. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Pruebas de anticuerpos', 'Las pruebas de anticuerpos revelan la presencia de anticuerpos antinucleares y anti-CCP, consistentes con el diagnóstico de artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos antiinflamatorios y se realizarán controles regulares para monitorear la progresión de la enfermedad.', 3, 4),

-- Paciente 4 (6 registros)
('2023-11-30', 'El paciente ha experimentado acidez estomacal frecuente y dolor abdominal. No hay antecedentes de enfermedades gastrointestinales en la familia.', 'Endoscopia', 'La endoscopia revela la presencia de úlceras gástricas y esofágicas, sugiriendo enfermedad por reflujo gastroesofágico.', 'Se recomendará una combinación de cambios en el estilo de vida y medicamentos para controlar los síntomas.', 4, 6),
('2023-10-18', 'El paciente presenta tos crónica y dificultad para respirar. No hay antecedentes de enfermedades respiratorias en la familia.', 'Radiografía de tórax', 'La radiografía de tórax muestra signos de consolidación pulmonar, indicando una posible neumonía.', 'Se prescribirá un curso de antibióticos y se realizará un seguimiento para evaluar la respuesta al tratamiento.', 4, 8),
('2023-09-10', 'El paciente ha experimentado dolor de espalda crónico y rigidez matutina. No hay antecedentes de enfermedades reumáticas en la familia.', 'Resonancia magnética de columna', 'La resonancia magnética revela signos de espondilitis anquilosante, una forma de artritis que afecta principalmente la columna vertebral.', 'Se prescribirá un tratamiento con antiinflamatorios no esteroides y se recomendará fisioterapia para mejorar la movilidad.', 4, 4),
('2023-08-05', 'El paciente ha experimentado cambios en los hábitos intestinales y sangrado rectal. No hay antecedentes de enfermedades gastrointestinales en la familia.', 'Colonoscopia', 'La colonoscopia revela la presencia de pólipos colorrectales y áreas de inflamación, sugiriendo colitis ulcerosa.', 'Se requerirá un tratamiento a largo plazo con medicamentos antiinflamatorios y se realizará un seguimiento regular con un gastroenterólogo.', 4, 9),
('2023-07-20', 'El paciente ha experimentado fatiga extrema y pérdida de apetito. No hay antecedentes de enfermedades hepáticas en la familia.', 'Ecografía abdominal', 'La ecografía abdominal muestra signos de hepatomegalia y dilatación de la vía biliar, indicando posible enfermedad hepática.', 'Se requerirá una evaluación adicional para determinar la causa subyacente de los hallazgos y se discutirán opciones de tratamiento una vez que se conozca el diagnóstico.', 4, 15),
('2023-06-15', 'El paciente ha experimentado picazón en la piel y erupciones cutáneas. No hay antecedentes de enfermedades cutáneas en la familia.', 'Biopsia cutánea', 'La biopsia cutánea muestra signos de dermatitis atópica, una enfermedad inflamatoria crónica de la piel.', 'Se recomendará un tratamiento con cremas emolientes y corticosteroides tópicos para controlar los síntomas.', 4, 18),

-- Paciente 5 (6 registros)
('2023-11-25', 'El paciente ha experimentado dolor abdominal y cambios en los hábitos intestinales. No hay antecedentes de enfermedades gastrointestinales en la familia.', 'Colonoscopia', 'La colonoscopia revela la presencia de pólipos colorrectales y áreas de inflamación en el colon, sugiriendo colitis ulcerosa.', 'Se requerirá un tratamiento a largo plazo con medicamentos antiinflamatorios y se realizará un seguimiento regular con un gastroenterólogo.', 5, 9),
('2023-10-12', 'El paciente ha experimentado dolor en las articulaciones y rigidez matutina. No hay antecedentes de enfermedades reumáticas en la familia.', 'Análisis de sangre', 'Los análisis de sangre muestran niveles elevados de factor reumatoide y PCR, indicando posible artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos antiinflamatorios y se realizará un seguimiento regular con un reumatólogo.', 5, 4),
('2023-09-05', 'El paciente ha experimentado fatiga extrema, pérdida de peso y fiebre intermitente. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Pruebas de anticuerpos', 'Las pruebas de anticuerpos revelan la presencia de anticuerpos antinucleares y anti-CCP, consistentes con el diagnóstico de artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos inmunosupresores y se realizarán controles regulares para monitorear la progresión de la enfermedad.', 5, 4),
('2023-08-18', 'El paciente ha experimentado inflamación y dolor en las articulaciones, especialmente en las manos y los pies. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Radiografía articular', 'La radiografía muestra signos de erosión ósea y cambios articulares característicos de la artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos antirreumáticos modificadores de la enfermedad (DMARD) para controlar la inflamación y proteger las articulaciones.', 5, 11),
('2023-07-02', 'El paciente presenta erupciones cutáneas y picazón intensa. No hay antecedentes de enfermedades cutáneas en la familia.', 'Biopsia de piel', 'La biopsia de piel muestra cambios histopatológicos compatibles con el diagnóstico de psoriasis.', 'Se prescribirán tratamientos tópicos y se recomendarán cambios en el estilo de vida para controlar los síntomas.', 5, 18),
('2023-06-10', 'El paciente ha experimentado dificultad para respirar y opresión en el pecho. No hay antecedentes de enfermedades cardíacas en la familia.', 'Prueba de función pulmonar', 'La prueba de función pulmonar muestra una disminución del volumen espiratorio forzado en el primer segundo (FEV1), indicando posible enfermedad pulmonar obstructiva crónica (EPOC).', 'Se requerirá un tratamiento con broncodilatadores y corticosteroides inhalados para mejorar la función pulmonar.', 5, 20),

-- Paciente 6 (5 registros)
('2023-12-12', 'El paciente ha experimentado mareos y desmayos frecuentes. No hay antecedentes de enfermedades cardíacas en la familia.', 'Electrocardiograma', 'El electrocardiograma muestra una arritmia cardíaca con intervalos PR prolongados, indicando un posible bloqueo cardíaco.', 'Se requiere un monitoreo cardíaco continuo y se considerará la colocación de un marcapasos si persisten los síntomas.', 6, 2),
('2023-11-28', 'El paciente ha experimentado dolor en el pecho y dificultad para respirar durante el ejercicio. No hay antecedentes de enfermedades cardíacas en la familia.', 'Ecocardiograma', 'El ecocardiograma muestra signos de disfunción sistólica del ventrículo izquierdo, indicando posible insuficiencia cardíaca.', 'Se derivará al paciente a un cardiólogo para una evaluación más detallada y se discutirán opciones de tratamiento.', 6, 14),
('2023-10-10', 'El paciente ha experimentado fatiga extrema, pérdida de peso y fiebre intermitente. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Pruebas de anticuerpos', 'Las pruebas de anticuerpos revelan la presencia de anticuerpos antinucleares y anti-CCP, consistentes con el diagnóstico de artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos inmunosupresores y se realizarán controles regulares para monitorear la progresión de la enfermedad.', 6, 4),
('2023-09-02', 'El paciente ha experimentado inflamación y dolor en las articulaciones, especialmente en las manos y los pies. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Radiografía articular', 'La radiografía muestra signos de erosión ósea y cambios articulares característicos de la artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos antirreumáticos modificadores de la enfermedad (DMARD) para controlar la inflamación y proteger las articulaciones.', 6, 11),
('2023-08-20', 'El paciente presenta erupciones cutáneas y picazón intensa. No hay antecedentes de enfermedades cutáneas en la familia.', 'Biopsia de piel', 'La biopsia de piel muestra cambios histopatológicos compatibles con el diagnóstico de psoriasis.', 'Se prescribirán tratamientos tópicos y se recomendarán cambios en el estilo de vida para controlar los síntomas.', 6, 18),

-- Paciente 7 (6 registros)
('2023-12-15', 'El paciente ha experimentado fatiga extrema, debilidad muscular y temblores. No hay antecedentes de enfermedades neuromusculares en la familia.', 'Electromiografía', 'La electromiografía muestra signos de disfunción neuromuscular, indicando posible miastenia gravis.', 'Se requerirá un tratamiento con inhibidores de la acetilcolinesterasa y posiblemente inmunoterapia para controlar los síntomas.', 7, 3),
('2023-11-30', 'El paciente ha experimentado dolor abdominal y cambios en los hábitos intestinales. No hay antecedentes de enfermedades gastrointestinales en la familia.', 'Endoscopia', 'La endoscopia revela la presencia de pólipos colorrectales y áreas de inflamación en el colon, sugiriendo colitis ulcerosa.', 'Se requerirá un tratamiento a largo plazo con medicamentos antiinflamatorios y se realizará un seguimiento regular con un gastroenterólogo.', 7, 9),
('2023-10-25', 'El paciente presenta fatiga extrema, pérdida de peso y fiebre intermitente. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Análisis de sangre', 'Los análisis de sangre muestran niveles elevados de factor reumatoide y PCR, indicando posible artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos antiinflamatorios y se realizará un seguimiento regular con un reumatólogo.', 7, 4),
('2023-09-18', 'El paciente ha experimentado inflamación y dolor en las articulaciones, especialmente en las manos y los pies. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Radiografía articular', 'La radiografía muestra signos de erosión ósea y cambios articulares característicos de la artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos antirreumáticos modificadores de la enfermedad (DMARD) para controlar la inflamación y proteger las articulaciones.', 7, 11),
('2023-08-12', 'El paciente presenta erupciones cutáneas y picazón intensa. No hay antecedentes de enfermedades cutáneas en la familia.', 'Biopsia de piel', 'La biopsia de piel muestra cambios histopatológicos compatibles con el diagnóstico de psoriasis.', 'Se prescribirán tratamientos tópicos y se recomendarán cambios en el estilo de vida para controlar los síntomas.', 7, 18),
('2023-07-28', 'El paciente ha experimentado episodios de confusión y pérdida de memoria. No hay antecedentes de enfermedades neurológicas en la familia.', 'Resonancia magnética cerebral', 'La resonancia magnética muestra signos de atrofia cerebral y placas de desmielinización, consistentes con el diagnóstico de esclerosis múltiple.', 'Se requerirá un tratamiento inmunomodulador para controlar la progresión de la enfermedad y se ofrecerá apoyo para manejar los síntomas.', 7, 17),

-- Paciente 8 (5 registros)
('2023-12-20', 'El paciente ha experimentado dolores de cabeza intensos y visión borrosa. No hay antecedentes de enfermedades oculares en la familia.', 'Examen de vista', 'Se diagnostica miopía en ambos ojos, con una graduación de -3 dioptrías en el ojo derecho y -2.5 dioptrías en el ojo izquierdo.', 'Se recomienda el uso de anteojos con las especificaciones proporcionadas y se realizará un seguimiento oftalmológico anual.', 8, 19),
('2023-11-25', 'El paciente ha experimentado fatiga extrema, pérdida de peso y fiebre intermitente. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Pruebas de anticuerpos', 'Las pruebas de anticuerpos revelan la presencia de anticuerpos antinucleares y anti-CCP, consistentes con el diagnóstico de artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos inmunosupresores y se realizarán controles regulares para monitorear la progresión de la enfermedad.', 8, 4),
('2023-10-18', 'El paciente ha experimentado inflamación y dolor en las articulaciones, especialmente en las manos y los pies. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Radiografía articular', 'La radiografía muestra signos de erosión ósea y cambios articulares característicos de la artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos antirreumáticos modificadores de la enfermedad (DMARD) para controlar la inflamación y proteger las articulaciones.', 8, 11),
('2023-09-12', 'El paciente presenta erupciones cutáneas y picazón intensa. No hay antecedentes de enfermedades cutáneas en la familia.', 'Biopsia de piel', 'La biopsia de piel muestra cambios histopatológicos compatibles con el diagnóstico de psoriasis.', 'Se prescribirán tratamientos tópicos y se recomendarán cambios en el estilo de vida para controlar los síntomas.', 8, 18),
('2023-08-28', 'El paciente ha experimentado dificultad para respirar y opresión en el pecho. No hay antecedentes de enfermedades cardíacas en la familia.', 'Prueba de función pulmonar', 'La prueba de función pulmonar muestra una disminución del volumen espiratorio forzado en el primer segundo (FEV1), indicando posible enfermedad pulmonar obstructiva crónica (EPOC).', 'Se requerirá un tratamiento con broncodilatadores y corticosteroides inhalados para mejorar la función pulmonar.', 8, 20),

-- Paciente 9 (4 registros)
('2023-12-25', 'El paciente ha experimentado dolor abdominal y cambios en los hábitos intestinales. No hay antecedentes de enfermedades gastrointestinales en la familia.', 'Colonoscopia', 'La colonoscopia revela la presencia de pólipos colorrectales y áreas de inflamación en el colon, sugiriendo colitis ulcerosa.', 'Se requerirá un tratamiento a largo plazo con medicamentos antiinflamatorios y se realizará un seguimiento regular con un gastroenterólogo.', 9, 9),
('2023-11-12', 'El paciente ha experimentado inflamación y dolor en las articulaciones, especialmente en las manos y los pies. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Radiografía articular', 'La radiografía muestra signos de erosión ósea y cambios articulares característicos de la artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos antirreumáticos modificadores de la enfermedad (DMARD) para controlar la inflamación y proteger las articulaciones.', 9, 11),
('2023-10-05', 'El paciente presenta erupciones cutáneas y picazón intensa. No hay antecedentes de enfermedades cutáneas en la familia.', 'Biopsia de piel', 'La biopsia de piel muestra cambios histopatológicos compatibles con el diagnóstico de psoriasis.', 'Se prescribirán tratamientos tópicos y se recomendarán cambios en el estilo de vida para controlar los síntomas.', 9, 18),
('2023-09-22', 'El paciente ha experimentado fatiga extrema, pérdida de peso y fiebre intermitente. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Pruebas de anticuerpos', 'Las pruebas de anticuerpos revelan la presencia de anticuerpos antinucleares y anti-CCP, consistentes con el diagnóstico de artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos inmunosupresores y se realizarán controles regulares para monitorear la progresión de la enfermedad.', 9, 4),

-- Paciente 10 (3 registros)
('2023-12-30', 'El paciente ha experimentado fatiga extrema, pérdida de peso y fiebre intermitente. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Pruebas de anticuerpos', 'Las pruebas de anticuerpos revelan la presencia de anticuerpos antinucleares y anti-CCP, consistentes con el diagnóstico de artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos inmunosupresores y se realizarán controles regulares para monitorear la progresión de la enfermedad.', 10, 4),
('2023-11-15', 'El paciente ha experimentado inflamación y dolor en las articulaciones, especialmente en las manos y los pies. No hay antecedentes de enfermedades autoinmunes en la familia.', 'Radiografía articular', 'La radiografía muestra signos de erosión ósea y cambios articulares característicos de la artritis reumatoide.', 'Se prescribirá un tratamiento con medicamentos antirreumáticos modificadores de la enfermedad (DMARD) para controlar la inflamación y proteger las articulaciones.', 10, 11),
('2023-10-02', 'El paciente presenta erupciones cutáneas y picazón intensa. No hay antecedentes de enfermedades cutáneas en la familia.', 'Biopsia de piel', 'La biopsia de piel muestra cambios histopatológicos compatibles con el diagnóstico de psoriasis.', 'Se prescribirán tratamientos tópicos y se recomendarán cambios en el estilo de vida para controlar los síntomas.', 10, 18);
COMMIT;